### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Powerbock** [Jafea7/RecFilter2#1]
Hello. first of all thank you for this ingenious program, even if I needed something to understand the sense in it. Meanwhile, the program runs stable in conjunction with ctbrec as well as standalone at ir under windows 10 as well as under Ubuntu 20. A technical question, since I have no idea of programming (unfortunately): the calculation / recognition of the patterns based on the images takes a relatively long time. Would I get a better speed when using a [Coral AI accelerator](https://coral.ai/products/accelerator) ? Is such a thing supported by the Python script, or could the program be adapted to it?

**Comment by Jafea7** [comment]
(Just a repeat of my reply on Discord):
Can't really tell you, Dema chose the AI engine and did the section of the script that works out what to keep from the returned analysis, I kind of added the rest, (config, image extraction, etc).  Seeing as NudeNet also has a TF-lite based classifier it should work on the Coral AI but as to how you'd go about it, I have no idea.
https://github.com/ndaysinaiK/nude-test - this seems to deal with the TF-lite implementation.
