### ISSUE TITLE
Win11 - Pathlib fails to install

### ISSUE THREAD

**Issue by Locknes** [Jafea7/RecFilter2#2]
Trying to run python -m pip install -r requirements.txt fails with the error
```PS C:\Users\GPUser\Documents\CTBRec Filter\RecFilter2-main> python -m pip install -r .\requirements.txt
Collecting requests
  Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 KB 3.3 MB/s eta 0:00:00
Collecting nudenet
  Downloading NudeNet-2.0.9-py3-none-any.whl (24 kB)
Collecting pathlib
  Using cached pathlib-1.0.1.tar.gz (49 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
Python v3.10.3
click      8.0.4
colorama   0.4.4
pep517     0.12.0
pip        22.0.3
pip-tools  6.5.1
setuptools 58.1.0
tomli      2.0.1
wheel      0.37.1

OS is fresh W11 installation

**Comment by Jafea7** [comment]
Can't help you with Windows 11, I'm only running 10, but it installs OK with the following:

Python 3.9.6
Package                Version
---------------------- ---------
NudeNet                2.0.9
pathlib                   1.0.1
pip                       22.0.4
requests                2.26.0
setuptools            56.0.0

None of the others listed above are installed on either of my Win10 machines.

EDIT: Python 3.9.10 works in a Win11 Hyper-V so there's something in 3.10 breaking it.

**Comment by Locknes** [comment]
I redeployed the machine, and 3.9.10 ran the requirement install fine, though I am now getting an error about "INVALID_PROTOBUF".
```
PS C:\Users\GPUVM\Documents\CTBRec Filter\RecFilter2-main> python RecFilter2.py C:\Users\GPUVM\Documents\NAME\file.mp4
Traceback (most recent call last):
  File "C:\Users\GPUVM\Documents\CTBRec Filter\RecFilter2-main\RecFilter2.py", line 13, in <module>
    detector = NudeDetector()
  File "C:\Users\GPUVM\AppData\Local\Programs\Python\Python39\lib\site-packages\nudenet\detector.py", line 57, in __init__
    self.detection_model = onnxruntime.InferenceSession(checkpoint_path)
  File "C:\Users\GPUVM\AppData\Local\Programs\Python\Python39\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\GPUVM\AppData\Local\Programs\Python\Python39\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 368, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\Users\GPUVM\.NudeNet/detector_v2_default_checkpoint.onnx failed:Protobuf parsing failed.
```

**Comment by Locknes** [comment]
I did also need to manually install Visual C++ Redistributable before the script would run.
This is on W10, 19044.1566

**Comment by Locknes** [comment]
Got it working after finding an identical issue in the CTBRec discord
https://discord.com/channels/758300181346910208/758300490500014110/937888017933299763

I'm not a dev, so not sure how git works, but probably worth updating the readme with the potential extra steps.
Thanks for the help!

**Comment by Jafea7** [comment]
The two files are part of the NudeNet git/setup and it looks like with the change in GitHub practices you now need to be logged in to GitHub fetch them.
They can be downloaded individually and placed in the appropriate directory using the URLs:
https://github.com/notAI-tech/NudeNet/releases/download/v0/detector_v2_default_checkpoint.onnx
https://github.com/notAI-tech/NudeNet/releases/download/v0/detector_v2_default_classes
